version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: golang:1.6-onbuild
    volumes:
      - '.:/app'
    ports:
      - '8080:8080'
      - '5000:5000'
    command: 'tail -f /dev/null'

